#!/bin/sh

case "$1" in
	--shortcut) exec /usr/bin/python3 -m faugus.shortcut "$2";;
	--game)     exec /usr/bin/python3 -m faugus.runner_core --game "$2";;
	--run)      exec /usr/bin/python3 -m faugus.runner_core "$2";;
	*)          exec /usr/bin/python3 -m faugus.launcher "$@";;
esac
